# Generated by Django 3.0.3 on 2020-02-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200214_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='room_number',
        ),
    ]
