# Generated by Django 3.0.3 on 2020-02-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_person_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='attendees_table',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='clients_table',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email_verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='events_table',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='remember_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
